baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Factorytype Blog'
theme = 'ananke'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
	 
	 [[menu.main]]
  name = "Custom Page"
  url = "/custom/my-page.html"
  weight = 50


